# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=20, default=0, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, default=0, max_digits=30)),
                ('type', models.CharField(choices=[('HOUSE', 'Casa'), ('APARTAMENT', 'Apartamento')], max_length=255, verbose_name='Tipo de moradia')),
                ('apartment', models.IntegerField(default=0, verbose_name='N\xfamero do apartamento')),
                ('internet', models.BooleanField(default=True, verbose_name='Tem internet')),
                ('rooms', models.IntegerField(default=2, verbose_name='N\xfamero de quartos')),
                ('comment', models.TextField(max_length=1048576, verbose_name='Coment\xe1rios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
