# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 06:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies', models.IntegerField(default=1, verbose_name='N\xfamero de vagas')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('begin', models.BigIntegerField(default=0, verbose_name='Data de in\xedcio do an\xfancio')),
                ('end', models.BigIntegerField(default=0, verbose_name='Data de t\xe9rmino do an\xfancio')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='building',
            field=models.CharField(default='', max_length=255, verbose_name='Nome do pr\xe9dio'),
        ),
        migrations.AddField(
            model_name='home',
            name='internetPrice',
            field=models.BooleanField(default=True, verbose_name='Mensalidade da internet'),
        ),
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor do aluguel'),
        ),
        migrations.AddField(
            model_name='home',
            name='residents',
            field=models.IntegerField(default=1, verbose_name='N\xfamero de moradores'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(default='', verbose_name='Link para o facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone principal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneSecondary',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone secund\xe1rio'),
        ),
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('HOUSE', 'Casa'), ('APARTAMENT', 'Apartamento')], default='HOUSE', max_length=255, verbose_name='Tipo de moradia'),
        ),
        migrations.AlterField(
            model_name='home',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL, verbose_name='Respons\xe1vel'),
        ),
        migrations.AddField(
            model_name='offer',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='api.Home', verbose_name='Moradia'),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Respons\xe1vel'),
        ),
    ]
