# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161225_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='internetPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Mensalidade da internet'),
        ),
    ]
